[project]
name = 'stacks-dao'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []


[contracts.dao-core-v5]
path = 'contracts/dao-core-v5.clar'
clarity_version = 4
epoch = '3.3'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
